### ISSUE TITLE
Issue 8/7/2020

### ISSUE THREAD

**Issue by e71az** [mikethreels/book_cover#2]
Hello Michael, your blog looks really nice, cant wait to see it finished! I still don't know anything about RoR so I cant help you out with code improvements but:

- Just remember to link everything as much as possible (make everything clickable with anchors).
- If you have extra time, try to implement an infinite scroll to your articles, that would be great!

Keep it going, HAPPY CODING, WAAAAARMMM

**Comment by mikethreels** [comment]
thank you Elias, I've made the adjustments
